#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#

library(shiny)

# Define UI for application that draws a plot and a table
shinyUI(fluidPage(
  
  # Application title
  titlePanel("Electricity Generation in Central States"),
  h5("In many central states in the U.S., electricity generated by wind farms is growing rapidly and displacing coal-fired electricity generation. These slides demonstrate that trend in the following states: Iowa, Kansas, Minnesota, North Dakota, Oklahoma, and Texas. The graphs only display the percentage of electricity generated from wind or coal, and do not show other electricity generation sources that may be present in those states."),
  h3("Instructions"),
  h5("Select a state from the dropdown menu. Select points using the cursor.
     Select the wind points, and the slope + intercept will tell you the year in which we
     could expect to have 100% wind electricity based on a simple linear trend.
     Select the coal points, and the intercept will tell you the year in which we could
     expect to have 0% coal electricity also based on a linear trend. You can use all
     data points from 2001 to 2016 or select a more recent subset.
     Obviously, in reality, electricity generation is a bit more complex than a linear model ;)"),
  # Have user select a state
  sidebarLayout(
    sidebarPanel(
       selectInput("dataset",
                   "Select a state",
                   choices = c("Iowa","Kansas","Minnesota",
                               "North Dakota","Oklahoma","Texas")),
       h3("Slope"),
       textOutput("slopeOut"),
       h3("Intercept"),
       textOutput("intOut")
    ),
    
    # Show the plot
    mainPanel(
       plotOutput("coalWindPlot", brush = brushOpts(
         id = "brush1"
       ))
    )
  ),
  h5("Data Source"),
  a("Energy Information Administration", href="https://www.eia.gov/electricity/data/browser/#/topic/0?agg=2,0,1&fuel=o08&geo=00000sg006&sec=g&freq=A&start=2001&end=2016&ctype=linechart&ltype=pin&rtype=s&pin=&rse=0&maptype=0")
))